service: knee-rehab-app-backend

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  timeout: 30
  stage: ${opt:stage, 'dev'}

functions:
  entidadesPrimarias:
    handler: lambda_entidades_primarias.main.handler
    events:
      - httpApi:
          path: /api/v1
          method: any

  instituciones:
    handler: lambda_instituciones.main.handler
    events:
      - httpApi:
          path: /api/v1
          method: any
