service: knee-rehab-app-backend

frameworkVersion: '3'

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.12
  region: us-east-1
  timeout: 30
  stage: ${opt:stage, 'dev'}

custom:
  pythonRequirements:
    dockerizePip: true    # instala en un contenedor Amazon Linux igual al de Lambda
    zip: true             # comprime las dependencias en el bundle
    slim: true            # elimina tests, docs y archivos no esenciales
    layer: false          # empaqueta directamente en tu función en lugar de en un layer

functions:
  entidadesPrimarias:
    handler: lambda_entidades_primarias.main.handler
    events:
      - httpApi:
          path: /entidades-primarias
          method: any

  instituciones:
    handler: lambda_instituciones.main.handler
    events:
      - httpApi:
          path: /instituciones
          method: any
  
  accesoPersonal:
    handler: lambda_acceso_personal.main.handler
    events:
      - httpApi:
          path: /acceso-personal
          method: any

  lesiones:
    handler: lambda_lesiones.main.handler
    events:
      - httpApi:
          path: /lesiones
          method: any

  recursosTerapeuticos:
    handler: lambda_recursos_terapeuticos.main.handler
    events:
      - httpApi:
          path: /recursos-terapeuticos
          method: any

  terapias:
    handler: lambda_terapias.main.handler
    events:
      - httpApi:
          path: /terapias
          method: any