service: knee-rehab-app-backend

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  timeout: 30

functions:
  entidadesPrimarias:
    handler: lambda_entidades_primarias.main.handler
    events:
      - httpApi:
          path: /api/v1/paises
          method: any

  rehab:
    handler: lambda_rehab.main.handler
    events:
      - httpApi:
          path: /api/v1/rehab
          method: any
