service: autentificador-api-aws

frameworkVersion: '3.40.0'

provider:
  name: aws
  runtime: python3.10
  stage: dev
  region: us-east-1
  environment:
    DATABASE_HOST: database.c476myam6hcq.us-east-1.rds.amazonaws.com
    DATABASE_PORT: 5432
    DATABASE_NAME: dbkneerehab
    DATABASE_USER: userkneerehab
    DATABASE_PASSWORD: LFS1ieqpA7bhuCK3W1Xo

    COGNITO_CLIENT_ID: 18ojcokska1igo3hrb743d6bt5
    COGNITO_CLIENT_SECRET: 1eim1p0a80bkrks410u4mlk5795lon8jkldrte1dr9mge75jfvbo
    COGNITO_METADATA_URL: https://cognito-idp.us-east-1.amazonaws.com/tu_pool_id/.well-known/openid-configuration
    USER_POOL_ID: us-east-1_ZU66EGIZV

    ACCESS_KEY_AWS: AKIA43IBNFXXZGJRU5QI
    SECRET_KEY_AWS: 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

functions:
  api:
    handler: autentificador.app.main.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: any

package:
  patterns:
    - '!node_modules/**'
    - '!.serverless/**'
    - '!.venv/**'
    - '!.git/**'
    - '!.vscode/**'
    - '!tests/**'
    - '!*.pyc'
    - '!__pycache__/**'
    - 'autentificador/**'
    - 'requirements.txt'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    zip: false
    slim: false
    pythonBin: python3

  serverless-offline:
    httpPort: 3000
    lambdaPort: 3002
    noPrependStageInUrl: true
